# fly.toml app configuration file generated for nodejs-api on 2025-08-29T06:43:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nodejs-api'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

  [deploy]
  release_command = "npm run db:migrate"
